export const FETCH_POSTS_PENDING = 'posts/FETCH_POSTS_PENDING';
export const FETCH_POSTS_REJECTED = 'posts/FETCH_POSTS_REJECTED';
export const FETCH_POSTS_SUCCESS = 'posts/FETCH_POSTS_SUCCESS';
export const NEW_POSTS = 'posts/NEW_POST';
