export const REQUEST_SIGIN_PENDING = 'auth/REQUEST_SIGNIN_PENDING';
export const REQUEST_SIGIN_REJECTED = 'auth/REQUEST_SIGNIN_REJECTED';
export const REQUEST_SIGIN_SUCCESS = 'auth/REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNUP_PENDING = 'auth/REQUEST_SIGNUP_PENDING';
export const REQUEST_SIGNUP_REJECTED = 'auth/REQUEST_SIGNUP_REJECTED';
export const REQUEST_SIGNUP_SUCCESS = 'auth/REQUEST_SIGNUP_SUCCESS';

export default {
  REQUEST_SIGIN_PENDING,
  REQUEST_SIGIN_REJECTED,
  REQUEST_SIGIN_SUCCESS,
  REQUEST_SIGNUP_PENDING,
  REQUEST_SIGNUP_REJECTED,
  REQUEST_SIGNUP_SUCCESS,
};
